### ISSUE TITLE
FID on Fashion

### ISSUE THREAD

**Issue by HuMingqi** [AliaksandrSiarohin/sketch-gan#1]
I got a bad FID value(>100) on Fashion-mnist, I'm not sure it's the problem of methods or the statistics on Fashion training data/ test data which I calculated with the function in fid.py :
[`def calculate_activation_statistics(images, sess, batch_size=50, verbose=False`)](https://github.com/bioinf-jku/TTUR/blob/dc4e5b5d02e1dd59a53b1d466a046402a5f69891/fid.py#L159)
I repeated channels to rgb and then called it.
So could you send your precalculated statistics on Fashion train/test(like, xxx.npz) to my email(hiocde@gmail.com)? Thanks.

**Comment by AliaksandrSiarohin** [comment]
First: please note that you don't need to compute the statistics of GT data, it will be computed automatically if you just run the script ```CUDA_VISIBLE_DEVICES=0 fashionmnist_resnet_sn_uncond.sh```.
Second: most likelly it was a problem of the method, because I did some experiment and occasionally change default decomposition to 'zca', which from time to time can fail completely, now it is fixed. (If you have something like completely grey images, then this is the reason, you can check the images in output folder)
I also send you my statistics of fashion-mnist, but as I said it is not needed.
